services:
  nginx:
    build: ./docker/nginx
    ports:
      - 4444:80
    depends_on:
      - webapp-prod
    volumes:
      - ./prod_static:/static
    networks:
      prod:
  webapp-prod:
    extends:
      file: docker-compose.yml
      service: webapp
    build:
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn b2broker.wsgi:application
      --workers=2
      --threads=4
      --worker-class=gthread
      --bind :8000
      --worker-tmp-dir /dev/shm
      --capture-output"
    env_file:
      - ./env/prod.env
    volumes:
      - ./prod_static:/static
    depends_on:
      mysql-prod:
        condition: service_healthy
        restart: true
    networks:
      - prod
  mysql-prod:
    extends:
      file: docker-compose.yml
      service: mysql
    env_file:
      - ./env/prod.env
    volumes:
      - ./prod-dbdata:/var/lib/mysql/
    networks:
      - prod

networks:
  prod:
