services:
  pytest:
    env_file:
      - ./test.env
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile.test
    command: pytest -svv
    volumes:
      - ./src/b2broker:/app
    working_dir: /app
    depends_on:
      mysql-test:
        condition: service_healthy
        restart: true
    networks:
      - test
  mysql-test:
    extends:
      file: docker-compose.yml
      service: mysql
    env_file:
      - ./test.env
    networks:
      - test

networks:
  test:

