# Generated by Django 5.1 on 2024-08-21 13:38

import api.validators
import django.core.exceptions
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=0,
                        max_digits=27,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)), name="balance_gte_0"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "txid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        editable=False,
                        max_digits=24,
                        validators=[
                            api.validators.NonZeroValidator(
                                django.core.exceptions.ValidationError
                            )
                        ],
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.wallet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount", 0), _negated=True),
                        name="amount_ne_0",
                    )
                ],
            },
        ),
    ]
